# Generated by Django 3.1.3 on 2020-12-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201107_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-Date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-Created',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
    ]
