# Generated by Django 3.1.3 on 2020-12-25 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageHeading',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Tag',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')]),
        ),
    ]
