# Generated by Django 3.1.3 on 2020-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201225_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='Tag',
            field=models.CharField(max_length=200),
        ),
    ]
