# Generated by Django 3.1.3 on 2020-12-27 06:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201226_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-Date', '-pk')},
        ),
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
