# Generated by Django 3.1.3 on 2020-12-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_letsconnect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letsconnect',
            old_name='email',
            new_name='lc_email',
        ),
        migrations.RenameField(
            model_name='letsconnect',
            old_name='message',
            new_name='lc_message',
        ),
        migrations.RenameField(
            model_name='letsconnect',
            old_name='phone_no',
            new_name='lc_phone_no',
        ),
    ]
